programmer
  id    = "raspberry_pi_gpio";
  desc  = "Raspberry Pi GPIO via sysfs/libgpiod";
  type  = "linuxgpio";
  prog_modes  = PM_ISP;
  connection_type = linuxgpio;
  reset  = 18;
  sck    = 17;
  sdo    = 14;
  sdi    = 15;
;
